### ISSUE TITLE
A strongly-named assembly

### ISSUE THREAD

**Issue by semi07** [Sustainsys/Saml2#1368] opened 2022-09-21 04:43 UTC
I'm going to sign my application with certificate but I cannot do it because of Sustainsys.Saml2.dll and Sustainsys.Saml2.HttpModule.dll.
Please see it for more details - https://stackoverflow.com/questions/290980/error-a-strongly-named-assembly-is-required.

Could You sign yours dll's?

**Comment by AndersAbel** [comment] 2022-10-15 10:57
Duplicate of #198

**Closed by AndersAbel** 2022-10-15 10:57 UTC
Labels: enhancement, triage, no-issue-activity
