### ISSUE TITLE
Adding Subject to Saml2AuthenticationRequest

### ISSUE THREAD

**Issue by PeterThornley** [Sustainsys/Saml2#837] opened 2017-11-09 07:07 UTC
Hi there
Apologies if this is not the correct forum for this question...

I'm trying to add a <saml: subject> element to a Kentor.AuthServices.Saml2P.Saml2AuthenticationRequest but not having much luck.  When setting up the KentorAuthServicesAuthenticationOptions I can see that as part of the the Notifications we can assign the AuthenticationRequestCreated Action which would allow me to update the authentication request however  looking at the code I can't see anywhere that allows me to add a subject.  If possible please point me in the right direction to add this element.

On a side note, I'm trying to add the subject element in order to pass in the username that will *hopefully* be picked up in the ADFS login page and automatically populate the username field.  I have tried adding a query parameter to the SAML request e.g. 
https://adfsv3.domain.com/adfs/ls/?SAMLRequest=pZ...etc...moZ&username=user@domain.com and this works however it would be preferable to have the username in the SAML request.

Thanks in advance

**Comment by AndersAbel** [comment] 2017-11-13 10:04
The library doesn't (yet) support adding a Subject to the AuthnRequest. Duplicate of #430

**Closed by AndersAbel** 2017-11-13 10:04 UTC
