### ISSUE TITLE
Case-sensitive ModulePath

### ISSUE THREAD

**Issue by mrfatgoat** [Sustainsys/Saml2#847] opened 2017-11-15 22:40 UTC
In the AspNetCore2 project, `Saml2Handler` has the following check in `public Task<bool> HandleRequestAsync()`.

`if(context.Request.Path.StartsWithSegments(options.SPOptions.ModulePath, StringComparison.Ordinal))`

This performs a case-sensitive comparison between the specified ModulePath and the incoming URL segment.  Is this intentional or can this be loosened by using `StringComparison.OrdinalIgnoreCase`?

**Comment by mrfatgoat** [comment] 2017-11-15 22:43
Looks like this was asked once before for an older version: #570

**Comment by AndersAbel** [comment] 2017-11-16 05:57
Duplicate of #570

**Closed by AndersAbel** 2017-11-16 05:57 UTC
