### ISSUE TITLE
Fips compliance

### ISSUE THREAD

**Issue by egontier** [Sustainsys/Saml2#983] opened 2018-06-27 09:59 UTC
Hello,
I'm trying to make systainsys.saml2 work on a FIPS server. I updated all my nuget packages and modified my machines config like it's written [here ](https://github.com/Sustainsys/Saml2/pull/813/commits/50c794afb182e95078cdf1f3b6d27b4238392cbd)

But  i still have this error : 

`</samlp:Response>
AuthServices Error: 0 : Saml2 Authentication failed. The received SAML data is
<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" Destination="xxx" ID="_e7f1ef8c190bf36be4c910bd8f60b271" InResponseTo="idf2bd85784d8b4066ad7e646fbd4f2713" IssueInstant="2018-06-27T09:43:52Z" Version="2.0">
    <saml:Issuer>xxx</saml:Issuer>
    <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
<ds:SignedInfo>
<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
<ds:Reference URI="#_e7f1ef8c190bf36be4c910bd8f60b271">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
<ds:DigestValue>io5IiBD4NeQ5zzTP6lHRGF7qxvxhVoFWTqZvkWMEN7I=</ds:DigestValue>
</ds:Reference>
</ds:SignedInfo>
<ds:SignatureValue>
xxx
</ds:SignatureValue>
<ds:KeyInfo>
<ds:X509Data>
<ds:X509Certificate>
xx
</ds:X509Certificate>
</ds:X509Data>
<ds:KeyValue>
<ds:RSAKeyValue>
<ds:Modulus>
xxx
</ds:Modulus>
<ds:Exponent>AQAB</ds:Exponent>
</ds:RSAKeyValue>
</ds:KeyValue>
</ds:KeyInfo>
</ds:Signature><samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
    </samlp:Status>
    <saml:Assertion ID="_48e708f57be310cfcbe19599ba668f0d" IssueInstant="2018-06-27T09:43:52Z" Version="2.0">
        <saml:Issuer>xxx</saml:Issuer>
        <saml:Subject>
            <saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">CN=usr xxx,OU=BORDEAUX_MERIGNAC,OU=ATLANTIS,OU=AGENCES,DC=xxx,DC=pre</saml:NameID>
            <saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                <saml:SubjectConfirmationData InResponseTo="idf2bd85784d8b4066ad7e646fbd4f2713" NotOnOrAfter="2018-06-27T09:45:51Z" Recipient="xxx" />
            </saml:SubjectConfirmation>
        </saml:Subject>
        <saml:Conditions NotBefore="2018-06-27T09:42:51Z" NotOnOrAfter="2018-06-27T09:45:51Z">
            <saml:AudienceRestriction>
                <saml:Audience>xxx</saml:Audience>
            </saml:AudienceRestriction>
        </saml:Conditions>
        <saml:AuthnStatement AuthnInstant="2018-06-27T08:58:45Z" SessionIndex="_48e708f57be310cfcbe19599ba668f0d">
            <saml:AuthnContext>
                <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified</saml:AuthnContextClassRef>
            </saml:AuthnContext>
        </saml:AuthnStatement>
        <saml:AttributeStatement>
            <saml:Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name">
                <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">usr_proxysng1</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress">
                <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">xxx</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname">
                <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">xxx</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname">
                <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">usr</saml:AttributeValue>
            </saml:Attribute>
        </saml:AttributeStatement>
    </saml:Assertion>
</samlp:Response>
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
   at System.Security.Cryptography.SHA256Managed..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   at System.Security.Cryptography.SignatureDescription.CreateDigest()
   at System.Security.Cryptography.Xml.SignedXml.CheckSignedInfo(AsymmetricAlgorithm key)
   at System.Security.Cryptography.Xml.SignedXml.CheckSignature(AsymmetricAlgorithm key)
   at Sustainsys.Saml2.XmlHelpers.VerifySignature(IEnumerable`1 signingKeys, SignedXml signedXml, XmlElement signatureElement, Boolean validateCertificate)
   at Sustainsys.Saml2.XmlHelpers.IsSignedByAny(XmlElement xmlElement, IEnumerable`1 signingKeys, Boolean validateCertificate, String minimumSigningAlgorithm)
   at Sustainsys.Saml2.Saml2P.Saml2Response.ValidateSignature(IOptions options)
   at Sustainsys.Saml2.Saml2P.Saml2Response.<CreateClaims>d__57.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Sustainsys.Saml2.Saml2P.Saml2Response.GetClaims(IOptions options)
   at Sustainsys.Saml2.WebSso.AcsCommand.ProcessResponse(IOptions options, Saml2Response samlResponse, StoredRequestState storedRequestState)
   at Sustainsys.Saml2.WebSso.AcsCommand.Run(HttpRequestData request, IOptions options)
   at Sustainsys.Saml2.Owin.Saml2AuthenticationHandler.<AuthenticateCoreAsync>d__0.MoveNext()`

Someone can help me ? Maybe i have to do something else ?
I put the cryptographySettings at the end of my 2 machine.config.

Thanks for your help

**Comment by 0xfeeddeadbeef** [comment] 2018-06-28 13:44
What did you put inside `<cryptographySettings>`?
When FIPS is enabled, `CryptoConfig.CreateFromName("SHA256")` will return instance of `SHA256Cng` or `SHA256CryptoServiceProvider` (which are FIPS compliant) even without configuring anything in `machine.config`.
I am **guessing** you have something like this:
```xml
<configuration>
  <mscorlib>
    <cryptographySettings>
      <cryptoNameMapping>
        <cryptoClasses>
          <cryptoClass overrideSHA256="System.Security.Cryptography.SHA256Managed"/>
        </cryptoClasses>
        <nameEntry name="SHA256" class="overrideSHA256"/>
        <nameEntry name="System.Security.Cryptography.SHA256" class="overrideSHA256"/>
      </cryptoNameMapping>
    </cryptographySettings>
  </mscorlib>
</configuration>
```
which would be wrong and cause exception you are having.
Either remove `SHA256` mapping or map it to FIPS compliant class: `SHA256Cng` (or `SHA256CryptoServiceProvider`).

**Comment by egontier** [comment] 2018-07-03 10:06
Hei George,

Thank you for your answer.
I've tried maybe 10 different cryptographySettings and each time i've got the same error it tries to create the  SHA256Managed :(
```
System.Security.Cryptography.SHA256Managed..ctor()
System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   at System.Security.Cryptography.SignatureDescription.CreateDigest()
   at System.Security.Cryptography.Xml.SignedXml.CheckSignedInfo(AsymmetricAlgorithm key)
   at System.Security.Cryptography.Xml.SignedXml.CheckSignature(AsymmetricAlgorithm key)
   at Sustainsys.Saml2.XmlHelpers.VerifySignature(IEnumerable`1 signingKeys, SignedXml signedXml, XmlElement signatureElement, Boolean validateCertificate)
```
This is my settings inside my machine config

```
	<cryptographySettings>
			<cryptoNameMapping>   
				<cryptoClasses>
					<cryptoClass SHA256CSP="System.Security.Cryptography.SHA256CryptoServiceProvider, System.Core, Version=4.0.0.0, PublicKeyToken=b77a5c561934e089" />
				</cryptoClasses>            
				<nameEntry name="SHA256" class="SHA256CSP" />
				<nameEntry name="SHA256CryptoServiceProvider" class="SHA256CSP" />
				<nameEntry name="System.Security.Cryptography.SHA256CryptoServiceProvider" class="SHA256CSP" /> 
				<nameEntry name="System.Security.Cryptography.SHA256" class="SHA256CSP"/>
				<nameEntry name="System.Security.Cryptography.SymmetricAlgorithm" class="SHA256CSP" />
        </cryptoNameMapping>  
    </cryptographySettings>
```
I also tried 
`<cryptoClass SHA256CSP="System.Security.Cryptography.SHA256Cng, System.Core, Version=4.0.0.0, PublicKeyToken=b77a5c561934e089" />` and its the same

Then i tried : 
`<cryptoClass SHA256CSP="System.Security.Cryptography.AesCryptoServiceProvider, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />`
And i've got this error : Unable to cast object of type 'System.Security.Cryptography.AesCryptoServiceProvider' to type 'System.Security.Cryptography.HashAlgorithm'. before the redirection to IDP.

With that error i assume my modification actually does something...

Of course if i don't put anything in my machine.config i still have the same error.

It's seem easy but i guess i'm missing something.

Thanks again for your help

**Comment by 0xfeeddeadbeef** [comment] 2018-07-03 13:02
This might be the reason: are you calling [Sustainsys.Saml2.Configuration.Options.GlobalEnableSha256XmlSignatures()](https://github.com/Sustainsys/Saml2/blob/9f0aca863dbd7b5d05c1db74c5299c7a28af339d/Sustainsys.Saml2/Configuration/Options.cs#L85) method from your code? Because it overrides whatever is registered in `machine.config` (and also default SHA2 algorithm) with non-FIPS `SHA256Managed` implementation.
If you do, remove it and try again.

**Comment by egontier** [comment] 2018-07-03 13:42
Thank's again George, that's the thing.
I've added GlobalEnableSha256XmlSignatures() because my application is targeting .net framework 4.5.1.

I have now this error : 
"SHA256 signatures require the algorithm to be registered at the process level. Upgrade to .Net 4.6.2 or call Sustainsys.Saml2.Configuration.Options.GlobalEnableSha256XmlSignatures() on startup to register."

My conclusion : do you confirm that FIPS and framework < 4.6.2 are not compatible ? Should i open a bug ?

**Comment by 0xfeeddeadbeef** [comment] 2018-07-03 15:39
No, that's not the case: FIPS and .NET < 4.6.2 are compatible, but these older versions of .NET are missing registered SHA-256 algorithm names & identifiers in `CryptoConfig`.

That's why `GlobalEnableSha256XmlSignatures()` method exists, which registers [ManagedSHA256SignatureDescription](https://github.com/Sustainsys/Saml2/blob/master/Sustainsys.Saml2/ManagedSha256SignatureDescription.cs) class (which is not FIPS-compliant, unfortunately).

So, you can say, that Sustainsys.Saml2 and FIPS are not compatible. Maybe later I will try and open a pull request with fix.

Meanwhile, you can try to use this workaround: [FipsSHA256SignatureDescription](https://gist.github.com/0xfeeddeadbeef/5a965519da969b8492015121596e7710).
I've modified existing `ManagedSHA256SignatureDescription` class to fall back to FIPS-compliant SHA256 when FIPS is enforced.
Include in your project and call after `GlobalEnableSha256XmlSignatures()` method:

```csharp
Options.GlobalEnableSha256XmlSignatures();

CryptoConfig.AddAlgorithm(typeof(FipsSHA256SignatureDescription), "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256");
```

It is important to call this after `GlobalEnableSha256XmlSignatures()`, because it re-registers SHA256 algorithm using FIPS-compliant implementation.

**Comment by egontier** [comment] 2018-07-04 08:46
Hello George,
Thanks again for your concern.

I've tried your workaround by puting your FipsSHA256SignatureDescription in my code.

```
         
app.UseSaml2Authentication(CreateSustainsysSamlOptions(_logger));

// Add compatibility for older .net framework
Options.GlobalEnableSha256XmlSignatures();

CryptoConfig.AddAlgorithm(typeof(FipsSHA256SignatureDescription), "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256");

```
With or without the cryptographySettings in the machine.config i have now the error bellow : ( if i understand what you have done i don't need to specify anything in the machine.config right ?)

```
System.Security.Cryptography.CryptographicException: Could not create hash algorithm object.
   at System.Security.Cryptography.Xml.Reference.CalculateHashValue(XmlDocument document, CanonicalXmlNodeList refList)
   at System.Security.Cryptography.Xml.SignedXml.CheckDigestedReferences()
   at System.Security.Cryptography.Xml.SignedXml.CheckSignature(AsymmetricAlgorithm key)
   at Sustainsys.Saml2.XmlHelpers.VerifySignature(IEnumerable`1 signingKeys, SignedXml signedXml, XmlElement signatureElement, Boolean validateCertificate)
   at Sustainsys.Saml2.XmlHelpers.IsSignedByAny(XmlElement xmlElement, IEnumerable`1 signingKeys, Boolean validateCertificate, String minimumSigningAlgorithm)
   at Sustainsys.Saml2.Saml2P.Saml2Response.ValidateSignature(IOptions options)
   at Sustainsys.Saml2.Saml2P.Saml2Response.<CreateClaims>d__57.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Sustainsys.Saml2.Saml2P.Saml2Response.GetClaims(IOptions options)
   at Sustainsys.Saml2.WebSso.AcsCommand.ProcessResponse(IOptions options, Saml2Response samlResponse, StoredRequestState storedRequestState)
   at Sustainsys.Saml2.WebSso.AcsCommand.Run(HttpRequestData request, IOptions options)
   at Sustainsys.Saml2.Owin.Saml2AuthenticationHandler.<AuthenticateCoreAsync>d__0.MoveNext()
```
I'm also thinking about my IDP, i'm using Sign&Go v7.0 and its using SHA-256 to sign SAML request. The problem could be that sign&go does not use FIPS compliant encryption method ?

**Comment by egontier** [comment] 2018-07-04 12:36
Well George thank you for your time.
I guess i only have two options left :
- migrate to .net framework 4.6.2
- disable FIPS on my server.
I'll try the first one.
Do not hesitate to keep me in touch if you create the pull request for that !

**Comment by AndersAbel** [comment] 2018-09-06 08:45
Is this a duplicate of #812?

**Closed** 2018-09-06 08:45 UTC
