### ISSUE TITLE
Using online stub IDP in ASP.NET Core 2.0 throws exception

### ISSUE THREAD

**Issue by EricSpeidel** [Sustainsys/Saml2#816] opened 2017-10-16 11:43 UTC
Somehow, using the local IDP that comes with the sample application the login process goes smoothly. However, when trying to use a different IDP with the Core2.0 implementation, the InResponseTo ID doesn't seem to be handled correctly. 
Here's what I did:

1. Build latest version from Github
2. Change Startup.cs in the provided SampleApplication (or adding it to any existing App) to add Saml2 Authentication like so:
`services.AddAuthentication()
                .AddSaml2(options => 
                {
                    options.SPOptions.EntityId = new EntityId("https://localhost:44342/AuthServices");
                    options.IdentityProviders.Add(
                        new IdentityProvider(
                            new EntityId("http://stubidp.kentor.se/Metadata"), options.SPOptions)
                        {
                            LoadMetadata = true
                        });
                });`
3. Start the application using, go to Login using Google Chrome, select Saml2. I get redirected to http://stubidp.kentor.se as expected, my incoming AuthnRequest looking like this: 
`
<saml2p:AuthnRequest xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" ID="ide9909172900b4622b2e34a32389b6e09" Version="2.0" IssueInstant="2017-10-16T11:41:23Z" Destination="http://stubidp.kentor.se/" AssertionConsumerServiceURL="https://localhost:44342/Saml2/Acs">
  <saml2:Issuer>https://localhost:44342/AuthServices</saml2:Issuer>
</saml2p:AuthnRequest>` as verified by the IDP (notably, the ID was received by the IDP and is echoed back to the SP as it should be). 

However, upon "logging in", it breaks with the following exception:

`Kentor.AuthServices.Exceptions.UnexpectedInResponseToException occurred
  HResult=0x80131500
  Message=Received message contains unexpected InResponseTo "ide9909172900b4622b2e34a32389b6e09". No cookie preserving state from the request was found so the message was not expected to have an InResponseTo attribute. This error typically occurs if the cookie set when doing SP-initiated sign on have been lost.
  Source=Kentor.AuthServices
  StackTrace:
   at Kentor.AuthServices.Saml2P.Saml2Response.ReadAndValidateInResponseTo(XmlElement xml, Saml2Id expectedInResponseTo) in C:\Users\EricSpeidel\source\repos\Saml2-master (3)\Saml2-master\Kentor.AuthServices\Saml2P\Saml2Response.cs:line 125
   at Kentor.AuthServices.Saml2P.Saml2Response..ctor(XmlElement xml, Saml2Id expectedInResponseTo) in C:\Users\EricSpeidel\source\repos\Saml2-master (3)\Saml2-master\Kentor.AuthServices\Saml2P\Saml2Response.cs:line 83
   at Kentor.AuthServices.WebSso.AcsCommand.Run(HttpRequestData request, IOptions options) in C:\Users\EricSpeidel\source\repos\Saml2-master (3)\Saml2-master\Kentor.AuthServices\WebSso\AcsCommand.cs:line 76
   at Sustainsys.Saml2.AspNetCore2.Saml2Handler.HandleRequestAsync() in C:\Users\EricSpeidel\source\repos\Saml2-master (3)\Saml2-master\Sustainsys.Saml2.AspNetCore2\Saml2Handler.cs:line 109
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
`
Is there further configuration required? Or is this an issue with how it handles requests in the current Core 2.0 state? Or possibly an issue with the stubidp at kentor.se? I don't seem to have an issue when using the local stubidp, which is weird. Don't currently have any other IDPs to test it with.

**Comment by AndersAbel** [comment] 2017-10-19 09:12
Duplicate of #809

**Closed by AndersAbel** 2017-10-19 09:12 UTC

**Comment by explunit** [comment] 2017-10-21 16:21
SameSite cookies issue -- see discussion in #809
