### ISSUE TITLE
Kentor Redirection Twice and InResponseTo issue

### ISSUE THREAD

**Issue by hmarcelodn** [Sustainsys/Saml2#517] opened 2016-06-30 17:04 UTC
Hello,

I am trying to use kentor in my local application and it redirect me back to kentor twice and after that throw the following error:

Received message contains unexpected InResponseTo "idc5f5e54065ca405d9986d4d24c450f0a". No RelayState was detected so message was not expected to have an InResponseTo attribute.

How can i solve it? 

Regards.

**Comment by AndersAbel** [comment] 2016-07-01 08:21
Can you use the browser debugging tools to get the complete redirect chain?

Also, what is your `returnUrl` setting?

**Comment by hmarcelodn** [comment] 2016-07-01 14:27
Hi Abel, See below de configuration:

			Options.GlobalEnableSha256XmlSignatures();

            var options = new KentorAuthServicesAuthenticationOptions(false)
            {
                AuthenticationType = authenticationType,
                SPOptions = new SPOptions
                {
                    EntityId = new EntityId(ConfigurationManager.AppSettings["EntityId"]),
                    ModulePath = "/saml/" + authenticationType + "/",
                    ReturnUrl = new Uri("https://localhost/bsp/Account/ExternalLoginCallback")
                }
            };

            options.SPOptions.ServiceCertificates.Add(new X509Certificate2(
                AppDomain.CurrentDomain.SetupInformation.ApplicationBase + "/App_Data/Kentor.AuthServices.Tests.pfx"));

            var idp = new IdentityProvider(providerId, options.SPOptions)
			{
				AllowUnsolicitedAuthnResponse = true,
				Binding = Saml2BindingType.HttpRedirect,
				SingleSignOnServiceUrl = new Uri(providerUrl)
			};

            idp.SigningKeys.AddConfiguredKey(certificate);

            options.IdentityProviders.Add(idp);

			app.UseKentorAuthServicesAuthentication(options);

**Comment by hmarcelodn** [comment] 2016-07-01 14:41
ProviderId: http://stubidp.kentor.se/982440c7-41dd-4702-b645-079a6a55befa/Metadata
ProviderUrl: http://stubidp.kentor.se/982440c7-41dd-4702-b645-079a6a55befa
ProviderMetadataUrl: http://stubidp.kentor.se/982440c7-41dd-4702-b645-079a6a55befa/Metadata

I am using the stub Idp from your Kentor page.

**Comment by hmarcelodn** [comment] 2016-07-01 18:17
![image](https://cloud.githubusercontent.com/assets/5897525/16530510/d9e35180-3f9e-11e6-8db8-c6642a0e0bf1.png)

**Comment by AndersAbel** [comment] 2016-07-04 08:14
That's strange.

Although I can see in the last image that it is indeed accessing stubidp.kentor.se again, I can't see why. Did you get a 303 from any previous response that redirects the user there?

**Comment by hmarcelodn** [comment] 2016-07-04 13:31
@AndersAbel Here is the complete trace after clicking login at Kentor.

![image](https://cloud.githubusercontent.com/assets/5897525/16561982/66199742-41d2-11e6-8220-a034aa6d34f0.png)

**Comment by AndersAbel** [comment] 2016-07-06 20:08
I don't see the problem. First you have the post from AuthServices that is part the login sequence. It correctly causes a request to ~/AuthServices/ACS which redirects to ~/Account/ExternalLoginCallback which redirects to /bsp/. At that point the user should be logged in.

I have no idea why there is a second request to the stubidp at #709.

**Comment by robinvanpoppel** [comment] 2016-12-27 08:40
We're experiencing these kind of errors as well in production. I've not been able to reproduce this behaviour on our local/test environments. We're gathering more information and will hopefully be able to find the cause as well.

**Comment by GaurangPoolCar** [comment] 2017-01-20 00:59
Hi Guys,

Any update on this issue. 

We also experiencing same issue. We sends an auth request to our IdP and after successful authentication, the IdP sends an assertion with the status of success with all the end users attributes to /AuthServices/Acs. Then system does a http 302 redirect back to the IdP asking it to authenticate the user again, but as this is SSO the end user is already logged into SSO, so it just redirects the user back to system with a successful assertion. 

So the question I have is why is the SP (service provider) not accepting the assertion when the assertion is valid with all the user attributes passed.

We are getting errors "No RelayState was detected so message was not expected to have an InResponseTo attribute.
   at Kentor.AuthServices.Saml2P.Saml2Response.ReadAndValidateInResponseTo(XmlElement xml, Saml2Id expectedInResponseTo)"

**Comment by fethier** [comment] 2017-01-24 20:59
Hi,

After deploying to production we also had users reporting this problem. After further investigation, this error popped because of users hitting backspace and going back to the /AuthServices/Acs.

Maybe we could validate that the HTTP Referer is not from returnUrl before throwing this error?

This might not be related to the problem OP has but I wanted to share since this page is a top result when searching for this error.

**Comment by dh-ger** [comment] 2017-03-20 11:25
See following issue and proposed workaround

https://github.com/KentorIT/authservices/issues/666#issuecomment-287458495

**Comment by AndersAbel** [comment] 2017-03-28 11:04
Closing this, guessing that it occurs when the user presses the back button. Please see #666 for a discussion on that.

If anyone sees this problem and can reproduce it (without hitting the browser back button), please comment and I'll reopen the issue.

**Comment by inventti-gabriel** [comment] 2017-03-31 19:51
I'm facing this issue too, and it's not related to the back button.
To reproduce, just set the "SampleMvcApplication" to run in the Local IIS and change the Web.config to the corresponding address (entityId and returnUrl).

**Comment by AndersAbel** [comment] 2017-03-31 19:53
@inventti-gabriel Thanks, I'll try that to get a reproduction and see if I can debug it.

**Comment by inventti-gabriel** [comment] 2017-04-03 20:58
I "solved" my problem, I guess the problem have something to do with my IIS or Firefox, but I don't know what exactly did to solve, sorry.

**Comment by AndersAbel** [comment] 2017-04-04 12:34
@inventti-gabriel Thanks for updating. I'm starting to think that this might have something to do with browsers prefetching URLs (that are reachable through GET).

**Closed** 2022-04-11 20:21 UTC
Labels: bug
