### ISSUE TITLE
Saml2/logout url creating an Authentication Request instead of a Logout Request

### ISSUE THREAD

**Issue by xavierjordisdg** [Sustainsys/Saml2#1165] opened 2020-03-11 10:30 UTC
Hi,

I have an ASP.NET website that handles authentication using nuget packages Sustainsys.Saml2 and Sustainsys.Saml2.HttpModule v2.2.0. I'm using .NETFramework v4.6.1.

Login works correctly. However, when I redirect to ~/saml2/logout, the URL is modified to ~/saml2/signin and an authentication request is sent instead of a logout request.

The IdP Sign On and Log Out URLs are the same, as you can see in the below configuration:

```
<?xml version="1.0"?>
<configuration>
  <configSections>
    <section name="system.identityModel" type="System.IdentityModel.Configuration.SystemIdentityModelSection, System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089"/>
    <section name="system.identityModel.services" type="System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection, System.IdentityModel.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=B77A5C561934E089"/>
    <section name="sustainsys.saml2" type="Sustainsys.Saml2.Configuration.SustainsysSaml2Section, Sustainsys.Saml2"/>
  </configSections>
  <system.webServer>
    <modules>
      <add name="SessionAuthenticationModule" type="System.IdentityModel.Services.SessionAuthenticationModule, System.IdentityModel.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
      <add name="Saml2AuthenticationModule" type="Sustainsys.Saml2.HttpModule.Saml2AuthenticationModule, Sustainsys.Saml2.HttpModule"/>
    </modules>
  </system.webServer>
  <sustainsys.saml2 publicOrigin="https://<sp_url>" entityId="https://<sp_url>" returnUrl="https://<sp_url>/" authenticateRequestSigningBehavior="Always">
    <nameIdPolicy allowCreate="true"/>
    <identityProviders>
      <add entityId="https://<idp_id>" signOnUrl="https://<idp_id>/protocol/saml" logoutUrl="https://<idp_id>/protocol/saml" allowUnsolicitedAuthnResponse="true" binding="HttpPost" wantAuthnRequestsSigned="true">
        <signingCertificate storeName="xxxx" storeLocation="xxx" findValue="xxxx" x509FindType="FindBySubjectName"/>
      </add>
    </identityProviders>
    <serviceCertificates>
      <add use="Signing" storeName="xxxx" storeLocation="LocalMachine" findValue="xxxx" x509FindType="FindBySubjectName"/>
    </serviceCertificates>
  </sustainsys.saml2>
  <system.identityModel>
    <identityConfiguration>
      <securityTokenHandlers>
        <add type="System.IdentityModel.Services.Tokens.MachineKeySessionSecurityTokenHandler, System.IdentityModel.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
        <remove type="System.IdentityModel.Tokens.SessionSecurityTokenHandler, System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
      </securityTokenHandlers>
    </identityConfiguration>
  </system.identityModel>
  <system.identityModel.services>
    <federationConfiguration>
      <cookieHandler requireSsl="true"/>
    </federationConfiguration>
  </system.identityModel.services>
</configuration>
```

Thanks!

**Comment by AndersAbel** [comment] 2020-03-17 08:24
Are you sure that the SAML2 Logout endpoint is really executed? This could be because of authorization rules blocking access to ~/saml2/logout causing a redirect to ~/saml2/login.

**Comment by xavierjordisdg** [comment] 2020-03-17 17:35
Hi,

Thanks for your reply. I've been doing some tests. I federated to the stubidp and the logout response is actually sent and everything works correctly. However, when I use the client's IdP, the user is logged out in the service provider but no logout response is sent to the IdP.

I've analysed the saml messages and I've noticed that no AuthnStatement is sent along in the authentication response. Is it possible that that information is necessary for the Logout request to be sent? Are there any requirements for the Logout response to be sent apart from adding a certificate for the Service Provider?

**Comment by AndersAbel** [comment] 2020-03-18 09:31
> I've analysed the saml messages and I've noticed that no AuthnStatement is sent along in the authentication response. Is it possible that that information is necessary for the Logout request to be sent? Are there any requirements for the Logout response to be sent apart from adding a certificate for the Service Provider?

Yes, for single logout to work, there must be a SessionIndex which is located in the AuthnStatement. If you enable logging, the Saml2 library outputs an extensive list of the checks done when it decides if it can do a federated logout or not.

https://github.com/Sustainsys/Saml2/blob/0859e67392ea613fcb82a8d7e0e9a6c1c4de6ab6/Sustainsys.Saml2/WebSSO/LogOutCommand.cs#L171

Closing, as this is apparently caused by the Idp.

**Closed by AndersAbel** 2020-03-18 09:31 UTC

**Comment by xavierjordisdg** [comment] 2020-03-18 10:24
Hi,

Is there any particular reason for that?

According to page 61 of the SAML specification (https://www.oasis-open.org/committees/download.php/35711/sstc-saml-core-errata-2.0-wd-06-diff.pdf),
the SessionIndex is only optional, as the session can be identified by the NameId.

**Comment by AndersAbel** [comment] 2020-03-18 10:39
> According to page 61 of the SAML specification (https://www.oasis-open.org/committees/download.php/35711/sstc-saml-core-errata-2.0-wd-06-diff.pdf),
> the SessionIndex is only optional, as the session can be identified by the NameId, the BaseId or the EncryptedId.

The SessionIndex is optional in general, but mandatory if Single Logout is used. The requirement is defined on page 19 of the profile spec https://www.oasis-open.org/committees/download.php/56782/sstc-saml-profiles-errata-2.0-wd-07.pdf

> If the identity provider supports the Single Logout profile, defined in Section 4.4, any authentication statements MUST include a SessionIndex attribute to enable per-session logout requests by the service provider.

**Comment by xavierjordisdg** [comment] 2020-03-18 12:12
Ok thank you! I asked for the IdP to be modified and it's working correctly now
