### ISSUE TITLE
Idsv3 Post Redirect Logout and KentorIT Authservices

### ISSUE THREAD

**Issue by federicobarera** [Sustainsys/Saml2#423] opened 2016-03-06 06:00 UTC
Follow up on: https://github.com/KentorIT/authservices/issues/421.

Discussion on implementation of the Post Redirect Logout feature of Idsv with Kentor Authservices.

**Comment by federicobarera** [comment] 2016-03-06 06:12
I created a sample app for that to show the flow.
This approach didn't require any change in the core library. The result tho is a pretty hacky middleware override.

https://github.com/KentorIT/authservices/pull/424

**Comment by AndersAbel** [comment] 2016-03-14 10:16
The middleware is quite hacky - yes. IMHO the problem is how the IdSrv3 logout flow is implemented. If it can be improved, no such hack will be needed. Did you see the IdentityServer/IdentityServer3#2613 ticket? With that implemented a lot of this won't be needed.

**Comment by AndersAbel** [comment] 2018-09-05 14:29
IdSrv3 support will not be improved, focus will be on asp.net core and IdSrv4. Closing.

**Closed by AndersAbel** 2018-09-05 14:29 UTC
