### ISSUE TITLE
.NET Framework - Certificate - PrivateKey - CryptographicException

### ISSUE THREAD

**Issue by mauricio-ramalho** [Sustainsys/Saml2#1298] opened 2021-06-28 15:46 UTC
Hello,

I am using Sustainsys SAML2 with OWIN to add federated authentication to a webapp running on .NET Framework 4.6.1.

We wrote a PoC code and it's working as expected when the certificate used to encrypt/decrypt is loaded from a .pfx file in the file system.

We're now actually implementing it and found that when the .pfx certificate is imported into the Windows store, loaded into the webapp and added to `SPOptions.ServiceCertificates` collection, Sustainsys SAML2 throws a 

`new ArgumentException(@"Provided certificate is not valid for encryption/decryption. There may be insufficient permissions to its private key in the windows certificate store or the certificate itself may not have the correct purposes. If you only want to use it for signing, set the Use property to Signing (CertificateUse.Signing).");`

in https://github.com/Sustainsys/Saml2/blob/v2/Sustainsys.Saml2/Configuration/ServiceCertificateCollection.cs due to a CryptographicException being thrown when accessing `certificate.PrivateKey`.

Turns out that accessing PrivateKey directly is discouraged as it cannot handle RSACng properly. The proper way to access the PrivateKey should be using the certificate.GetRSAPrivateKey() extension method.

https://www.pkisolutions.com/accessing-and-using-certificate-private-keys-in-net-framework-net-core/

**Comment by explunit** [comment] 2021-06-28 16:44
This may be true, but are you sure it's the real cause of your issue? If the same certificate works when loaded from pfx then the problem is likely that the private key permission in windows cert store is not granted to to the app pool account for your web application.

**Comment by mauricio-ramalho** [comment] 2021-06-28 22:15
Hello, thanks for the quick reply.

Yes, I'm sure. If I call `certificate.GetRSAPrivateKey()` after loading it from the store, I can access the private key, so no missing permissions for the user running the app. I also modified Sustainsys SAML2 source to call this method instead of `certificate.PrivateKey` in ServiceCertificateCollection and I got an exception in a different place.

I'm using a self-signed certificate. Maybe Windows changes to CNG after the certificate is imported to the store and Sustainsys SAML2 can no longer handle the private key.

**Comment by Tecknoth** [comment] 2021-07-01 06:48
You can try to export your certificate out of the store and load it from the file directly, that way you would know if the store is implied in some way. Did you try that already ?

**Comment by davidefu** [comment] 2021-08-07 12:43
Hi,
I've resolved setting the permission of the private key here
![image](https://user-images.githubusercontent.com/17928925/128600505-2892f6da-3993-4ab7-8300-388fe89dab65.png)
![image](https://user-images.githubusercontent.com/17928925/128600501-6a15b64d-baa4-4531-8742-e6d192f5637a.png)

**Comment by mauricio-ramalho** [comment] 2021-08-16 10:08
@davidefu this was not a permissions issue. It was due to the RSA algorithm used by the certificate (RSAcng).

The certificate that was causing the exception was a self-signed generated by IIS. After getting a "properly" generated certificate, there was no issue with Sustainsys.

Still, the usage of `certificate.PrivateKey` should be avoided to prevent this.

**Comment by AndersAbel** [comment] 2021-08-17 07:06
The access of `certificate.PrivateKey` was introduced back when it was common for certificates to be generated with a crypto service provider that didn't support SHA256. That magic should all be removed now. It's almost 8 years since I started this project now, and the .NET echo system has evolved a lot during that time.

**Comment by microalps** [comment] 2021-09-14 20:20
@mauricio-ramalho do you have a certificate file that reproduces this issue or even better a test case to confirm this is fixed in #1307?

**Closed** 2022-04-11 16:06 UTC
Labels: bug
