### ISSUE TITLE
Encrypted Assertions encountered but Service Certificate was not provided

### ISSUE THREAD

**Issue by msekkappan** [Sustainsys/Saml2#886] opened 2018-01-16 20:12 UTC
I have this configuration

            ServiceCertificate se = new ServiceCertificate()
            {
                Certificate = new X509Certificate2("Kentor.AuthServices.Tests.pfx"),
                Use = CertificateUse.Both
            };

            SPOptions sp = new SPOptions();
            sp.AuthenticateRequestSigningBehavior = SigningBehavior.Always;
            sp.EntityId = new EntityId("https://<name>/test/AuthServices");
            sp.ReturnUrl = new Uri("https://test");
            sp.ServiceCertificates.Add(se);

            IdentityProvider idp = new IdentityProvider(new EntityId("https://<test>/test"), sp);
            idp.Binding = Saml2BindingType.HttpPost;
            idp.WantAuthnRequestsSigned = true;
            idp.SingleSignOnServiceUrl = new Uri("https://<test>/sign");
            //idp.LoadMetadata = true;
            idp.SigningKeys.AddConfiguredKey(new X509Certificate2("test.pem"));

            services.AddAuthentication()
                .AddSaml2(options =>
                {
                    options.IdentityProviders.Add(idp);
                });

While decrypting, I get the subject error at

````
private static IEnumerable<X509Certificate2> GetCertificatesValidForDecryption(IOptions options)
        {
            var decryptionCertificates = options.SPOptions.DecryptionServiceCertificates;
````
decryptionCertificates collection has 0 length.  What am I missing?  The IDP logs successful auth and returns RSA-SHA256 encrypted certificate back.

**Comment by AndersAbel** [comment] 2018-01-23 10:12
@msekkappan If you are using encrypted assertions, you need to set a serviceCertifcate in SPOptions.

**Comment by msekkappan** [comment] 2018-01-24 16:10
Yes, I have it set as sp.ServiceCertificates.Add(se), see above code.

**Comment by AndersAbel** [comment] 2018-01-24 17:46
Looks like something to debug.

**Comment by Janidbest** [comment] 2018-03-02 06:41
have you found the root cause? I have the same issue today. The saml response is encrypted. but I can't configure the decryptioncertificate having a public key of IDP. 
The below fails 
>  options.SPOptions.ServiceCertificates.Add(new ServiceCertificate
>                     {
>                         MetadataPublishOverride = MetadataPublishOverrideType.DoNotPublish,
>                         Certificate = GetIdpCertificate(),
>                         Use=CertificateUse.Both
>                     });

The below is of no use, expected to set the servicecertificate for future use in decryption
> options.SPOptions.DecryptionServiceCertificates

**Comment by explunit** [comment] 2018-03-27 13:16
@msekkappan I see you define an `sp` variable but I don't see that you ever assign it to `options.SPOptions`. Can you clarify if that's happening outside the code snippet you posted?

**Comment by msekkappan** [comment] 2018-03-27 14:49
Certificate gets add by this code
sp.ServiceCertificates.Add(se);

I still have this issue, in the test environment we removed the encryption for now.  I am still looking for an answer.

**Comment by explunit** [comment] 2018-03-27 14:52
Right, but where does `sp` get added to anything?

**Comment by msekkappan** [comment] 2018-03-27 17:38
SP got added to idp in 
IdentityProvider idp = new IdentityProvider(new EntityId("https://<test>/test"), sp);

**Comment by explunit** [comment] 2018-03-27 17:45
I'm less familiar with the .net core version, but I would have expected to see it here:
```
         services.AddAuthentication()
            .AddSaml2(options =>
            {
                options.SPOptions = sp;
                options.IdentityProviders.Add(idp);
            });
```

**Comment by explunit** [comment] 2018-04-03 18:45
closing due to inactivity

**Closed by explunit** 2018-04-03 18:45 UTC
Labels: question

**Comment by msekkappan** [comment] 2018-04-27 17:51
I am not sure what changed, but it works now.
